name: Integracion continua.cpp

on:
  push_request:
    brances: [ master ]

jobs:
  ci_ti_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        whit:
          node-version: 10
      - run: npm ci
      - run: npm test
      - run: npm build